dispatcher/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<dispatch_id>\w+)/$', 'dispatcher.views.dispatch'),
]

shortio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from dispatcher.views import dispatch
from shortio import settings
from shorts.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='home'),
    url(r'^shorts/', include('shorts.urls', namespace='urls')),
    url(r'^api/', include('shorts.urls', namespace='api')),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^accounts/', include('allauth.urls')),
    url(r'^(?P<dispatch_id>\w+)$', dispatch),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shorts/urls.py
from django.conf.urls import include, url

from shorts import views
from .api import UrlList, UrlDetail, UserUrlList
# from .api import UserList, UserDetail

user_urls = [
    url(r'^(?P<username>[0-9a-zA-Z_-]+)/urlss$', UserUrlList.as_view(), name='userurl-list'),
    # url(r'^(?P<username>[0-9a-zA-Z_-]+)$', UserDetail.as_view(), name='user-detail'),
    # url(r'^$', UserList.as_view(), name='user-list')
]

urls_urls = [
    url(r'^(?P<pk>\d+)$', UrlDetail.as_view(), name='urls-detail'),
    url(r'^$', UrlList.as_view(), name='urls-list')
]

urlpatterns = [
    url(r'^users', include(user_urls)),
    url(r'^urls', include(urls_urls)),
    url(r'^$', views.index, name='index'),
    url(r'^create', views.create, name='create'),
    url(r'^(?P<url_id>\d+)/$', views.detail, name='detail')
]

dispatcher/models.py
from django.db import models

# Create your models here.

shorts/models.py
import random
import string

import logging
from django.conf import settings
from django.db import models
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.crypto import get_random_string

"""
class User(AbstractUser):
    followers = models.ManyToManyField('self',
                                       related_name='followees',
                                       symmetrical=False)
"""


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class Url(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_urls', null=True, blank=True)
    url = models.CharField(max_length=2048)
    shortened_url = models.CharField(max_length=6, unique=True)
    date_created = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.url


@receiver(post_save, sender=Url, dispatch_uid="create_url_slug")
def create_url_slug(sender, instance, **kwargs):

    if instance.shortened_url:
        return

    chars = 'abcdefghijklmnopqrstuvwxyz'
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    '0123456789'
    '_.-~'

    try:
        instance.shortened_url = get_random_string(4)  # create one
        found_slug = True
        while found_slug:  # keep checking until we have a valid slug
            found_slug = False
            other_objs_with_slug = type(instance).objects.filter(shortened_url=instance.shortened_url)
            if len(other_objs_with_slug) > 0:
                # if any other objects have current slug
                found_slug = True
            if found_slug:
                # create another slug and check it again
                instance.shortened_url = get_random_string(4, allowed_chars=chars)
        instance.save()
    except Exception as ex:
        logging.error(ex)

dispatcher/views.py
# Create your views here.
from django.http.response import Http404, HttpResponseRedirect

from core import url
from shorts.models import Url


def dispatch(request, dispatch_id):
    try:
        u = Url.objects.get(shortened_url=dispatch_id)
        return HttpResponseRedirect(u.url)
    except Url.DoesNotExist:
        raise Http404()

shorts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from shorts.models import Url
# Create your views here.


def index(request, error=None):
    latest_url_list = Url.objects.order_by('-date_created')[:5]
    context = {'latest_url_list': latest_url_list, 'error_message': error}
    return render(request, 'index.html', context)


def detail(request, url_id):
    url = get_object_or_404(Url, pk=url_id)
    return render(request, 'detail.html', {'url': url})


def create(request):
    try:
        u = Url(url=request.POST['url'])
        u.save()
    except Exception as ex:
        return index(request, error=ex.message)
    else:
        return HttpResponseRedirect(reverse('urls:index'))

shorts/templates/base.html
{% load staticfiles %}
{% load urls_extras %}
{% load compress %}
<html>
<head>
<title>ShortIO</title>
{% compress css %}
<link rel="stylesheet" type="text/css" href="{% static "themes/wed/css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "themes/wed/snippet.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "themes/wed/snippet.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/site.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-social.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}">
{% endcompress %}
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body ng-app="shortioApp" style="background-image: url('{% get_random_image %}');">
<div ng-include="'{% static "js/app/views/header.html" %}'"></div>
<div class="bootshape login-form">
    <div class="col-sm-6 col-md-5 col-lg-4 col-sm-offset-2 text-center login-popup-wrap">
        <div class="login-popup">
            <h1 class="title"><strong>ShortIO</strong></h1>
            <aside>all your shorts are belong to us</aside>
        </div>
        <div ng-include="'{% static "js/app/views/url.html" %}'"></div>
    </div>
</div>
{% compress js %}
<script src="{% static "js/underscore/underscore.js" %}"></script>
<script src="{% static "js/angular/angular.min.js" %}"></script>
<script src="{% static "js/angular/angular-resource.min.js" %}"></script>
<script src="{% static "js/angular/ui-bootstrap.js" %}"></script>
<script src="{% static "js/zepto.js" %}"></script>
<script src="{% static "js/script.js" %}"></script>

<script src="{% static "js/app/app.js" %}"></script>
<script src="{% static "js/app/directives/enter.js" %}"></script>
<script src="{% static "js/app/controllers/header.js" %}"></script>
<script src="{% static "js/app/controllers/url.js" %}"></script>
<script src="{% static "js/app/services/url.js" %}"></script>

{% endcompress %}
<script type="text/javascript">
    angular.module('shortioApp')
        .factory('AuthUser', function ($resource) {
            return {
                username: "{{ user.username|default:''|escapejs }}"
            }
        });
</script>
</body>
</html>

shorts/templates/detail.html
{{ url }}

shorts/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>HELLO SAILOR!</h1>
<form action="{% url 'urls:create' %}" method="post">
    {% csrf_token %}
    <label for="url">Url: </label>
    <input type="text" id="url" name="url" value="">
    <input type="submit"/>
</form>

{% if error_message %}
<h5>{{ error_message }}</h5>
{% endif %}

{% if latest_url_list %}
<ul>
    {% for url in latest_url_list %}
    <li><a href="{% url 'urls:detail' url.id %}">{{ url.url }}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load urls_extras %}
{% load compress %}
<html>
<head>
<title>ShortIO</title>
{% compress css %}
<link rel="stylesheet" type="text/css" href="{% static "themes/wed/css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "themes/wed/snippet.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "themes/wed/snippet.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/site.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-social.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}">
{% endcompress %}
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body ng-app="shortioApp" style="background-image: url('{% get_random_image %}');">
<div ng-include="'{% static "js/app/views/header.html" %}'"></div>
<div class="bootshape login-form">
    <div class="col-sm-6 col-md-5 col-lg-4 col-sm-offset-2 text-center login-popup-wrap">
        <div class="login-popup">
            <h1 class="title"><strong>Ferglie</strong></h1>
            <aside>all your shorts are belong to us</aside>
        </div>
        <div ng-include="'{% static "js/app/views/url.html" %}'"></div>
    </div>
</div>
{% compress js %}
<script src="{% static "js/underscore/underscore.js" %}"></script>
<script src="{% static "js/angular/angular.min.js" %}"></script>
<script src="{% static "js/angular/angular-resource.min.js" %}"></script>
<script src="{% static "js/angular/ui-bootstrap.js" %}"></script>
<script src="{% static "js/zepto.js" %}"></script>
<script src="{% static "js/script.js" %}"></script>

<script src="{% static "js/app/app.js" %}"></script>
<script src="{% static "js/app/directives/enter.js" %}"></script>
<script src="{% static "js/app/controllers/header.js" %}"></script>
<script src="{% static "js/app/controllers/url.js" %}"></script>
<script src="{% static "js/app/services/url.js" %}"></script>

{% endcompress %}
<script type="text/javascript">
    angular.module('shortioApp')
        .factory('AuthUser', function ($resource) {
            return {
                username: "{{ user.username|default:''|escapejs }}"
            }
        });
</script>
</body>
</html>

templates/dialogs/login.html
{% load socialaccount %}
<div class="modal-header login_modal_header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h2 class="modal-title" id="myModalLabel">Login to Your Account</h2>
</div>
<div class="modal-body login-modal">
    <p>Logging in allows you to save your shorts and view statistics</p>
    <br/>

    <div class="clearfix"></div>
    <div id='social-icons-conatainer'>
        <div class='modal-body-left'>
            <div class="form-group">
                <input type="text" id="username" placeholder="Enter your name" value=""
                       class="form-control login-field">
                <i class="fa fa-user login-field-icon"></i>
            </div>

            <div class="form-group">
                <input type="password" id="login-pass" placeholder="Password" value="" class="form-control login-field">
                <i class="fa fa-lock login-field-icon"></i>
            </div>

            <a href="#" class="btn btn-success modal-login-btn">Login</a>
            <a href="#" class="login-link text-center">Lost your password?</a>
        </div>

        <div class='modal-body-right'>
            <div class="modal-social-icons">
                <a href="{% provider_login_url "facebook" method="oauth2" %}"} class="btn btn-block btn-social btn-facebook">
                    <i class="fa fa-facebook"></i> Sign in with Facebook
                </a>
                <a href="{% provider_login_url "twitter" method="js_sdk" %}"} class="btn btn-block btn-social btn-twitter">
                    <i class="fa fa-twitter"></i> Sign in with Twitter
                </a>
                <a href="{% provider_login_url "google" method="js_sdk" %}"} class="btn btn-block btn-social btn-google-plus">
                    <i class="fa fa-google-plus"></i> Sign in with Google
                </a>
                <a href="{% provider_login_url "stackexchange" method="js_sdk" %}"} class="btn btn-block btn-social btn-stackexchange">
                    <i class="fa fa-stack-exchange"></i> Sign in with Stackexchange
                </a>
                <a href="{% provider_login_url "github" method="js_sdk" %}"} class="btn btn-block btn-social btn-github">
                    <i class="fa fa-github"></i> Sign in with Github
                </a>
            </div>
        </div>
        <div id='center-line'> OR</div>
    </div>
    <div class="clearfix"></div>

    <div class="form-group modal-register-btn">
        <button class="btn btn-default"> New User Please Register</button>
    </div>
</div>
<div class="clearfix"></div>
<div class="modal-footer login_modal_footer">
</div>

{% comment %}
<a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
{% endcomment %}